name: Update RaiPlaySound Feeds

on:
  schedule:
    - cron: "0 */6 * * *"  # Aggiorna ogni 6 ore
  workflow_dispatch:  # Permette di eseguirlo manualmente

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml feedendum

      - name: Generate Feeds
        run: python scripts/generate_feeds.py

      - name: Debug - Verifica file generati
        run: |
          echo "📂 Contenuto della directory:"
          ls -l
          echo "📜 Contenuto dei feed XML:"
          cat feed_*.xml || echo "⚠ Nessun file XML generato"

      - name: Commit and Push (con autenticazione)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feed_*.xml || true
          git diff --staged --quiet || (git commit -m "🔄 Aggiornamento automatico dei feed XML" && git push https://x-access-token:${GH_PAT}@github.com/giuliomagnifico/raiplay-feed.git main)
