name: Update RaiPlaySound Feeds

on:
  schedule:
    - cron: "0 */6 * * *"  # Aggiorna ogni 6 ore
  workflow_dispatch:  # Permette di eseguirlo manualmente

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Generate Feeds
        run: python scripts/generate_feeds.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add feed_*.xml
          git commit -m "🔄 Aggiornamento automatico dei feed XML" || echo "Nessuna modifica"
          git push
